version: "3.7"

services:

  redis:
    image: bitnami/redis:5.0.5-debian-9-r124
    container_name: redis
    environment:
      REDIS_PASSWORD: "P@ssw0rd"
    ports:
      - 6379:6379
    restart: on-failure
    networks:
      - coolstore

  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    restart: on-failure
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    restart: on-failure
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - coolstore

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: on-failure
    ports:
      - 9412:9411
    networks:
      - coolstore

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    restart: on-failure
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    depends_on:
      - promtail
    networks:
      - coolstore

  promtail:
    image: grafana/promtail:latest
    restart: on-failure
    volumes:
      - ./config/promtail.yml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - coolstore

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - coolstore

  # seq:
  #   image: datalust/seq
  #   container_name: seq
  #   restart: on-failure
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - 5341:5341
  #     - 5340:80
  #   networks:
  #     - coolstore

volumes:
  grafana:
  prometheus:
  promtail:

networks:
  coolstore:
    name: coolstore-network